### ISSUE TITLE
PythonScript: editor1 and editor2 should have auto-completion, too

### ISSUE THREAD

**Issue by pryrt** [molsonkiko/dictautocomp#1]
you can just duplicate the `editor.*` section for `editor1.` and `editor2.`

**Comment by molsonkiko** [comment]
I tested the plugin as is with multiple views open; it works fine (uses the correct autocompletions for the file in the active editor even if a file in the other editor has different autocompletions) no matter which view I'm in. Is there some very subtle error that I'm missing?

**Comment by pryrt** [comment]
I was just looking in `pythonscript_autocompletions.txt`, and noticed that you define all the methods for the `editor` instance of the `Editor` object, but not for the `editor1` and `editor2` instances.  Many of the scripts I write for PythonScript use `editor1.getText()` and `editor2.getText()` instead of just doing `editor.getText()` on the whichever view is active.  Looking at your autocomplete file, I am pretty sure that if I ever got your script to do anything for me (that's a different issue), it would only autcomplete if I use `editor.getT`, not if I started with `editor1.getT` , because there aren't any entries in your file for the `editor1` and `editor2` instances.

**Comment by molsonkiko** [comment]
Oh, thanks for the clarification. That'll be on my to-do list for the next release.

**Comment by pryrt** [comment]
confirmed that aa53eab works with `editor1` and `editor2` as well. thanks
