### ISSUE TITLE
How to get it to work

### ISSUE THREAD

**Issue by pryrt** [molsonkiko/dictautocomp#2]
your README.md seems to assume that the reader already knows how to get your "script" to work (despite there being multiple .py files in the repo, with no indication of which you actually should run"

I tried running `dictautocomp.py`: it prompted me and I filled out its form... but as I type, no autocompletions are happening.

I tried running just `get_pythonscript_autocompletions.py`, and couldn't see that anything happened.

Your README.md should include instructions on how to get it to register the callbacks, and what you have to do to trigger it to auto-complete (or if it's automatic).

**Comment by molsonkiko** [comment]
Yep, the documentation is severely lacking, and I'm going to work on it soon. Thanks for being my guinea pig!

`dictautocomp.py` is the correct file to run to start autocompletions, and if you don't get autocompletions after running it, that's a separate issue that I will need to resolve.

I think what I will do is just pre-fill the config file with the correct configuration to do autocompletions with the pythonscript autocompletions file, and that way users will have an example to go off of.

**Comment by molsonkiko** [comment]
@pryrt 
I've significantly improved the documentation, and I now believe based on a couple of trial runs that you should be able to get this running if you follow the `Installation` instructions in [README.md](https://github.com/molsonkiko/dictautocomp/blob/main/README.md).

It would be awesome if you could try following those instructions exactly as written, and let me know if there are still any problems for you. Thanks again for surfacing this issue for me.

**Comment by pryrt** [comment]
Yes, following those instructions, I was able to get it to work.

However, for newbies, I would add another section after **Installation**:

-----

## Using Dictionary Autocompletion
1. Run **Plugins > Python Script > `dictautocomp`**
2. It will pop up a dialog showing you the current configuration; you can hit **OK** here
3. It will pop up a second dialog: if you want to add a new dictionary, fill out the form and hit **OK**; otherwise, hit **Cancel** to not add another dictionary
4. If you are in a file whose extension that matches the "extensions" field from either the "current configuration" from step 2 or the new dictionary configuration you added in step 3, then as you type, the auto-completion will include the words from the dictionary
5. This auto-completion will continue until you exit Notepad++.  The next time you run the application, you will have to run this script again.

-----

**Comment by molsonkiko** [comment]
Good idea! I added your suggestions to the docs.

I also added a menu option `remove existing autocompletions for filename: no` (i.e., the default is NOT to remove existing autocompletions). Do you think the wording of this is clear enough?

**Comment by pryrt** [comment]
Thanks.  Looks good to me.
